# Generated by Django 5.2.9 on 2025-12-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_remuneração_funcionario_remuneracao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='data_nascimento',
        ),
    ]
